// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxBneqkucOcBe8nn6bF2AolAx4cdB_94',
    appId: '1:412395538950:web:a9a52ee8ca5a02b5f3d187',
    messagingSenderId: '412395538950',
    projectId: 'foodmanagement-3ca7c',
    authDomain: 'foodmanagement-3ca7c.firebaseapp.com',
    storageBucket: 'foodmanagement-3ca7c.firebasestorage.app',
    measurementId: 'G-JRKLQ8P05C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvlO6zAmL58-j2NstO-VYNauql7U-2abk',
    appId: '1:412395538950:android:5332da76c6ee96c5f3d187',
    messagingSenderId: '412395538950',
    projectId: 'foodmanagement-3ca7c',
    storageBucket: 'foodmanagement-3ca7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAchiQO9LDZuBCEaurbNfL6s4pJYir3Efo',
    appId: '1:412395538950:ios:abd4bbd6d33c74b8f3d187',
    messagingSenderId: '412395538950',
    projectId: 'foodmanagement-3ca7c',
    storageBucket: 'foodmanagement-3ca7c.firebasestorage.app',
    iosBundleId: 'com.example.managerestaurent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtxBneqkucOcBe8nn6bF2AolAx4cdB_94',
    appId: '1:412395538950:web:6fd8e460cc8647a2f3d187',
    messagingSenderId: '412395538950',
    projectId: 'foodmanagement-3ca7c',
    authDomain: 'foodmanagement-3ca7c.firebaseapp.com',
    storageBucket: 'foodmanagement-3ca7c.firebasestorage.app',
    measurementId: 'G-DNSRH5QS28',
  );
}
